name: Build A066 Kernel v6.1 (Clang 18 + Repack boot.img)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          gcc-aarch64-linux-gnu \
          gcc-arm-linux-gnueabi \
          bc bison flex libssl-dev libelf-dev \
          build-essential cpio python3

    - name: Install AOSP Prebuilt Clang (r530567)
      run: |
        wget https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/master/clang-r530567.tar.gz
        mkdir -p clang-prebuilt
        tar -xzf clang-r530567.tar.gz -C clang-prebuilt
        echo "$(pwd)/clang-prebuilt/bin" >> $GITHUB_PATH
        clang --version

    - name: Fix permissions for kernel scripts
      run: |
        chmod +x kernel-5.15/scripts/* || true
        chmod +x kernel-5.15/scripts/*/* || true
        chmod +x kernel-5.15/scripts/remove-stale-files || true
        if ! head -n1 kernel-5.15/scripts/remove-stale-files | grep -q '^#!'; then
          sed -i '1i #!/bin/sh' kernel-5.15/scripts/remove-stale-files
        fi

    - name: Build kernel (a06x_defconfig)
      run: |
        export ARCH=arm64
        export SUBARCH=arm64
        export CC=clang
        export LLVM=1
        export CROSS_COMPILE=aarch64-linux-gnu-
        export CROSS_COMPILE_ARM32=arm-linux-gnueabi-
        cd kernel-5.15
        make a06x_defconfig SHELL=/bin/bash
        make prepare SHELL=/bin/bash
        make -j$(nproc) SHELL=/bin/bash
        echo "✅ Build complete"
        ls -lh arch/arm64/boot/

       - name: Disable IKHEADERS (fix kheaders_data.tar.xz error)
      run: |
        cd kernel-5.15
        # đảm bảo có scripts/config
        make scripts
        # tắt IKHEADERS để không build kheaders_data.tar.xz
        ./scripts/config --disable IKHEADERS
        # regenerate config
        make olddefconfig

    - name: Upload Image.gz-dtb
      uses: actions/upload-artifact@v4
      with:
        name: Image.gz-dtb
        path: kernel-5.15/arch/arm64/boot/Image.gz-dtb

    - name: Pack with AnyKernel3
      run: |
        git clone https://github.com/osm0sis/AnyKernel3.git
        cp kernel-5.15/arch/arm64/boot/Image.gz-dtb AnyKernel3/
        cd AnyKernel3
        zip -r9 ../A066-Kernel-v6.1.zip ./*
        echo "✅ Packed AnyKernel3 zip"

    - name: Upload AnyKernel3 zip
      uses: actions/upload-artifact@v4
      with:
        name: A066-Kernel-v6.1
        path: A066-Kernel-v6.1.zip

    - name: Download stock boot.img from release
      run: |
        curl -L -o boot.img https://github.com/huyzilo77-bot/A066-5G/releases/download/V1/boot.img

    - name: Repack boot.img
      run: |
        git clone https://github.com/osm0sis/mkbootimg_tools.git
        mkdir boot_orig
        cd boot_orig
        ../mkbootimg_tools/unpackbootimg -i ../boot.img

        # Replace kernel with the new one
        cp ../kernel-5.15/arch/arm64/boot/Image.gz-dtb ./zImage

        # Repack boot.img
        ../mkbootimg_tools/mkbootimg \
          --kernel ./zImage \
          --ramdisk ./ramdisk.cpio.gz \
          --dtb ./dtb \
          --base $(cat boot.img-base 2>/dev/null || echo 0x40000000) \
          --pagesize $(cat boot.img-pagesize 2>/dev/null || echo 2048) \
          --cmdline "$(cat boot.img-cmdline 2>/dev/null)" \
          -o ../boot-new.img
        cd ..
        echo "✅ Repacked boot-new.img"

    - name: Upload repacked boot.img
      uses: actions/upload-artifact@v4
      with:
        name: boot-new
        path: boot-new.img