name: Build Kernels

permissions:
  contents: write
  actions: write

on:
  workflow_dispatch:

jobs:
  build-a13-5-15:
    uses: ./.github/workflows/kernel-a13-5-15.yml
    secrets: inherit

  release:
    runs-on: ubuntu-latest
    needs: [ build-a13-5-15 ]
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./downloaded-artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0
          prerelease: false
          files: ./downloaded-artifacts/**/*
          name: "Samsung A06 5G Kernel - Android 13 5.15"
          body: |
            Custom Kernel build for Samsung A06 5G (Android 13, kernel 5.15.151)
