name: Build Clean A066 Kernel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:   # Cho phép bạn chạy thủ công trên GitHub

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Setup toolchain (Proton Clang)
      run: |
        git clone --depth=1 https://github.com/kdrag0n/proton-clang toolchain

    - name: Build kernel (a06x_defconfig)
      run: |
        export PATH=$PWD/toolchain/bin:$PATH
        export ARCH=arm64
        export SUBARCH=arm64
        export CROSS_COMPILE=aarch64-linux-gnu-
        export CROSS_COMPILE_ARM32=arm-linux-gnueabi-
        cd kernel-5.15
        make a06x_defconfig
        make -j$(nproc)
        ls -lh arch/arm64/boot/

    - name: Pack with AnyKernel3
      run: |
        git clone https://github.com/osm0sis/AnyKernel3.git
        cp kernel-5.15/arch/arm64/boot/Image.gz-dtb AnyKernel3/
        cd AnyKernel3
        zip -r9 ../A066-Kernel-Clean.zip ./*

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: A066-Kernel-Clean
        path: A066-Kernel-Clean.zip
